version: '3'

services:

  redis:
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    links:
      - "postgres:database"
      - "redis:cash"
    depends_on:
      - postgres
      - redis
